**Task 04:**
*While dealing with the categorical data, there can be two cases such as ordinal and nominal. In the
nominal categorical data, there isn’t any kind of relationship in between the categories such as
category can be male or female and there isn’t any relationship or it cannot express any kind of  comparison etc. while in the ordinal category data, there is a clear relationship among categories or a kind of comparison such as the category data can be excellent, good, worst, average etc. The technique that deals with the nominal data is called as One-hot encoding while the technique deals with the ordinal data is called as ordinal encoding. Your task is to implement the ordinal encoding, label encoding and one-hot encoding. The implementation can be analyzed through different methods such as pandas and scikit-learn if possible.*

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [3]:
df=pd.read_csv('Raw.csv')
df.sample(5)

,id,case_one,case_two,date_time_column,Age,Gender,Department,City,Education_Level,Satisfaction,Performance,Salary,Experience_Years
125,126,A87,84,NaN,37,Male,Sales,Lahore,Master's,Low,Excellent,99819,9
221,222,B49,87,12/17/2020,26,Female,Finance,Lahore,PhD,Low,Poor,83085,4
269,270,BC85,61,NaN,49,Male,Marketing,Mardan,Bachelor's,Low,Good,110776,27
303,304,MN31,77,NaN,31,Female,Finance,Karachi,PhD,Medium,Good,130591,4
17,18,D98,45,NaN,41,Female,IT,Karachi,PhD,Medium,Good,53639,14

In [4]:
ordinal_columns = [
    "Education_Level",
    "Satisfaction",
    "Performance"
]

nominal_columns = [
    "Gender",
    "City",
    "Department"
]

In [5]:
ordinal_encoder = OrdinalEncoder(
    categories=[
        ["Bachelor's", "Master's", "PhD"],
        ["Low", "Medium", "High"],
        ["Poor", "Average", "Good", "Excellent"]
    ]
)

df_ordinal = df.copy()

df_ordinal[ordinal_columns] = ordinal_encoder.fit_transform(df_ordinal[ordinal_columns])

df_ordinal.sample(5)

,id,case_one,case_two,date_time_column,Age,Gender,Department,City,Education_Level,Satisfaction,Performance,Salary,Experience_Years
313,314,AB54,96,NaN,40,Female,IT,Mardan,0.0,2.0,0.0,69613,11
113,114,XY10,52,NaN,27,Male,Marketing,Quetta,0.0,1.0,2.0,134353,3
226,227,D4,59,NaN,42,Male,Marketing,Quetta,2.0,0.0,3.0,113039,15
207,208,XYZ17,4,NaN,30,Female,IT,Quetta,2.0,2.0,0.0,60437,1
333,334,A11,84,NaN,38,Female,Marketing,Lahore,0.0,2.0,0.0,92187,12

In [6]:
# Now let use the One Hot Endoder to encode the nominal columns

one_hot_encoder = OneHotEncoder(
    sparse_output=False,
    handle_unknown="ignore"
)

encoded_nominal = one_hot_encoder.fit_transform(
    df[nominal_columns]
)

encoded_nominal_df = pd.DataFrame(
    encoded_nominal,
    columns=one_hot_encoder.get_feature_names_out(nominal_columns)
)

print("\nOne-Hot Encoded Data:")
print(encoded_nominal_df)

One-Hot Encoded Data:
     Gender_Female  Gender_Male  City_Islamabad  City_Karachi  City_Lahore  \
0              0.0          1.0             0.0           0.0          0.0
1              0.0          1.0             0.0           0.0          0.0
2              0.0          1.0             0.0           0.0          0.0
3              1.0          0.0             0.0           0.0          0.0
4              0.0          1.0             1.0           0.0          0.0
..             ...          ...             ...           ...          ...
345            0.0          1.0             0.0           1.0          0.0
346            0.0          1.0             1.0           0.0          0.0
347            1.0          0.0             0.0           0.0          0.0
348            0.0          1.0             0.0           0.0          1.0
349            1.0          0.0             1.0           0.0          0.0

     City_Mardan  City_Peshawar  City_Quetta  Department_Finance  \
0            0.0            0.0          1.0                 0.0
1            0.0            0.0          1.0                 0.0
2            0.0            0.0          1.0                 0.0
3            1.0            0.0          0.0                 1.0
4            0.0            0.0          0.0                 0.0
..           ...            ...          ...                 ...
345          0.0            0.0          0.0                 0.0
346          0.0            0.0          0.0                 0.0
347          0.0            1.0          0.0                 0.0
348          0.0            0.0          0.0                 0.0
349          0.0            0.0          0.0                 1.0

     Department_HR  Department_IT  Department_Marketing  Department_Sales
0              1.0            0.0                   0.0               0.0
1              0.0            0.0                   0.0               1.0
2              0.0            0.0                   0.0               1.0
3              0.0            0.0                   0.0               0.0
4              0.0            1.0                   0.0               0.0
..             ...            ...                   ...               ...
345            1.0            0.0                   0.0               0.0
346            0.0            1.0                   0.0               0.0
347            0.0            1.0                   0.0               0.0
348            0.0            0.0                   0.0               1.0
349            0.0            0.0                   0.0               0.0

[350 rows x 13 columns]